# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model_server/protos/tensor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'model_server/protos/tensor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n model_server/protos/tensor.proto\x12\x0bModelServer\"\x13\n\x03\x44im\x12\x0c\n\x04size\x18\x01 \x01(\x05\"\x92\x01\n\x0bTensorProto\x12&\n\x0ctensor_shape\x18\x01 \x03(\x0b\x32\x10.ModelServer.Dim\x12\x12\n\nstring_val\x18\x02 \x03(\x0c\x12\x16\n\x0etensor_content\x18\x03 \x01(\x0c\x12!\n\x05\x64type\x18\x04 \x01(\x0e\x32\x12.ModelServer.DType\x12\x0c\n\x04name\x18\x05 \x01(\t*\\\n\x05\x44Type\x12\x0b\n\x07\x46LOAT32\x10\x00\x12\x0b\n\x07\x46LOAT16\x10\x01\x12\x0b\n\x07\x46LOAT64\x10\x02\x12\t\n\x05INT32\x10\x03\x12\t\n\x05UINT8\x10\x04\x12\n\n\x06STRING\x10\x05\x12\n\n\x06OBJECT\x10\x06\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_server.protos.tensor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DTYPE']._serialized_start=219
  _globals['_DTYPE']._serialized_end=311
  _globals['_DIM']._serialized_start=49
  _globals['_DIM']._serialized_end=68
  _globals['_TENSORPROTO']._serialized_start=71
  _globals['_TENSORPROTO']._serialized_end=217
# @@protoc_insertion_point(module_scope)
