__version__ = '0.1'
__author__ = 'Abhijit Balaji'
__title__ = 'model-server'
__summary__ = 'A Pure `python-3` based flexible gRPC server for hosting Deep Learning, Machine Learning models trained on any framework!'
__email__ = 'balaabhijit5@gmail.com'
