# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from model_server.apis import predict_pb2 as model__server_dot_apis_dot_predict__pb2
from model_server.protos import model_info_pb2 as model__server_dot_protos_dot_model__info__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in model_server/server_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ModelServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPredictions = channel.unary_unary(
                '/ModelServer.ModelServer/GetPredictions',
                request_serializer=model__server_dot_apis_dot_predict__pb2.PredictRequest.SerializeToString,
                response_deserializer=model__server_dot_apis_dot_predict__pb2.PredictResponse.FromString,
                _registered_method=True)
        self.GetModelInfo = channel.unary_unary(
                '/ModelServer.ModelServer/GetModelInfo',
                request_serializer=model__server_dot_protos_dot_model__info__pb2.ModelInfo.SerializeToString,
                response_deserializer=model__server_dot_protos_dot_model__info__pb2.ModelInfo.FromString,
                _registered_method=True)


class ModelServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPredictions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPredictions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPredictions,
                    request_deserializer=model__server_dot_apis_dot_predict__pb2.PredictRequest.FromString,
                    response_serializer=model__server_dot_apis_dot_predict__pb2.PredictResponse.SerializeToString,
            ),
            'GetModelInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelInfo,
                    request_deserializer=model__server_dot_protos_dot_model__info__pb2.ModelInfo.FromString,
                    response_serializer=model__server_dot_protos_dot_model__info__pb2.ModelInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ModelServer.ModelServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ModelServer.ModelServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModelServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPredictions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ModelServer.ModelServer/GetPredictions',
            model__server_dot_apis_dot_predict__pb2.PredictRequest.SerializeToString,
            model__server_dot_apis_dot_predict__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ModelServer.ModelServer/GetModelInfo',
            model__server_dot_protos_dot_model__info__pb2.ModelInfo.SerializeToString,
            model__server_dot_protos_dot_model__info__pb2.ModelInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
