# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model_server/server.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'model_server/server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from model_server.apis import predict_pb2 as model__server_dot_apis_dot_predict__pb2
from model_server.protos import model_info_pb2 as model__server_dot_protos_dot_model__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19model_server/server.proto\x12\x0bModelServer\x1a\x1fmodel_server/apis/predict.proto\x1a$model_server/protos/model_info.proto2\x9e\x01\n\x0bModelServer\x12M\n\x0eGetPredictions\x12\x1b.ModelServer.PredictRequest\x1a\x1c.ModelServer.PredictResponse\"\x00\x12@\n\x0cGetModelInfo\x12\x16.ModelServer.ModelInfo\x1a\x16.ModelServer.ModelInfo\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_server.server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODELSERVER']._serialized_start=114
  _globals['_MODELSERVER']._serialized_end=272
# @@protoc_insertion_point(module_scope)
