site_name: Model Server Documentation
docs_dir: sources
repo_url: https://github.com/Abhijit-2592/model-server
theme: readthedocs
site_author: Abhijit Balaji
dev_addr: '0.0.0.0:8000'
site_description: gRPC server for hosting Deep Learning/Machine Learning models trained on any framework.

nav:
  - Home: index.md
  - Core Docs:
    - Core: model_server.core
  - Utils Docs:
    - Model Info Utils: model_server.utils.model_info_utils
    - Prediction Utils: model_server.utils.prediction_utils
    - tensor Utils: model_server.utils.tensor_utils
