# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model_server/apis/predict.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'model_server/apis/predict.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from model_server.protos import tensor_pb2 as model__server_dot_protos_dot_tensor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fmodel_server/apis/predict.proto\x12\x0bModelServer\x1a model_server/protos/tensor.proto\"\xb1\x01\n\x0ePredictRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x37\n\x06inputs\x18\x02 \x03(\x0b\x32\'.ModelServer.PredictRequest.InputsEntry\x12\x0f\n\x07version\x18\x03 \x01(\t\x1aG\n\x0bInputsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.ModelServer.TensorProto:\x02\x38\x01\"\xb6\x01\n\x0fPredictResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12:\n\x07outputs\x18\x02 \x03(\x0b\x32).ModelServer.PredictResponse.OutputsEntry\x12\x0f\n\x07version\x18\x03 \x01(\t\x1aH\n\x0cOutputsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.ModelServer.TensorProto:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_server.apis.predict_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTREQUEST_INPUTSENTRY']._loaded_options = None
  _globals['_PREDICTREQUEST_INPUTSENTRY']._serialized_options = b'8\001'
  _globals['_PREDICTRESPONSE_OUTPUTSENTRY']._loaded_options = None
  _globals['_PREDICTRESPONSE_OUTPUTSENTRY']._serialized_options = b'8\001'
  _globals['_PREDICTREQUEST']._serialized_start=83
  _globals['_PREDICTREQUEST']._serialized_end=260
  _globals['_PREDICTREQUEST_INPUTSENTRY']._serialized_start=189
  _globals['_PREDICTREQUEST_INPUTSENTRY']._serialized_end=260
  _globals['_PREDICTRESPONSE']._serialized_start=263
  _globals['_PREDICTRESPONSE']._serialized_end=445
  _globals['_PREDICTRESPONSE_OUTPUTSENTRY']._serialized_start=373
  _globals['_PREDICTRESPONSE_OUTPUTSENTRY']._serialized_end=445
# @@protoc_insertion_point(module_scope)
